name = "Christoph U. Keller"
last_name = "Keller"
join_date = "2026-09-16"
affiliations = ["National Solar Observatory", "Leiden University"]
research_areas = ["Astrophysics", "Optics", "AI"]
bio = "I am an astronomer with experience in solar physics, exoplanets, remote sensing of the Earth's atmosphere and the design and development of innovative optical instruments. I am currently the director of the US National Solar Observatory."
