name = "Judith Sáinz-Pardo Díaz"
last_name = "Sáinz-Pardo Díaz"
join_date = "2026-09-16"
affiliations = ["Spanish National Research Council (CSIC) - Institute of Physics of Cantabria (IFCA)"]
research_areas = ["Federated AI", "Privacy-preserving AI", "Interoperability", "Data analysis"]
bio = "Judith Sáinz-Pardo holds a PhD in Science and Technology from the University of Cantabria, with a background in Mathematics and a Master's in Data Science. She is a Postdoctoral Researcher at the Advanced Computing and e-Science Group at the Institute of Physics of Cantabria (IFCA). She has worked in several European projects focused on AI, secure data management, AI-readiness, etc, including EOSC ARENA (serving as scientific coordinator), FLUID-AI, EOSC SIESTA, and AI4EOSC."
